### ISSUE TITLE
print'ов в коде не должно быть

### ISSUE THREAD

**Issue by coursar** [ElenaVeselovskaya/Gitdemo#5]
https://github.com/ElenaVeselovskaya/Gitdemo/blob/0f783d4af0ab628d6593aee7f4ee595ef40f2efd/cashback.py#L16

**Comment by coursar** [comment]
https://github.com/ElenaVeselovskaya/Gitdemo/blob/0f783d4af0ab628d6593aee7f4ee595ef40f2efd/bank_credit.py#L20

**Comment by ElenaVeselovskaya** [comment]
Исправлено.
см. aa31a766f2e9beb7b024b1951ed6cb326c94fa7f
